# Site settings
title: Frontend Raccoon
email: rtivital@gmail.com
description: Фронтенд и веб-разработка
url: "http://jsraccoon.ru"
twitter_username: rtivital
github_username:  rtivital

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values: 
      author: "Виталий Ртищев"
      layout: "post"
      type: article
      comments: true