# Site settings
title: Frontend Raccoon
email: rtivital@gmail.com
description: Фронтенд и веб-разработка
url: "http://jsraccoon.ru"
twitter_username: rtivital
github_username:  rtivital

# Build settings
# markdown: kramdown
markdown: redcarpet
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values: 
      author: "Виталий Ртищев"
      layout: "post"
      type: article
      comments: true

exclude: 
  - node_modules
  - bower_components
  - gulpfile.js
  - bower.json

gems:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"