# Site settings
title: Frontend Raccoon
email: rtivital@gmail.com
description: Фронтенд и веб-разработка
baseurl: "jsraccoon.ru"
url: "/"
twitter_username: rtivital
github_username:  rtivital

# Build settings
markdown: kramdown
permalink: /:title